### ISSUE TITLE
Review: 2. Good Commit Log messages

### ISSUE THREAD

**Issue by AxlLind** [johnnil/Lifelink#43]
Generally good descriptive commit messages but there are some outliers. For example the commit "Buttons #1", according to the commit message, starts working on and adds much more than just buttons.

I would also like to see more commit messages for the larger commits, for example the merging of pull requests. Not sure if you can add that in the merge commit itself but you can at least comment on the commit to say more about what it does.

**Comment by sinderwing** [comment]
It was a bit shaky in the beginning since I always realized stuff was a bit off when I tried to implement new things, hence the enormous changes to add a few buttons.

Is your profile pic the first randomly generated to properly look like something? It's a castle tower, albeit with weirdly long "spikes". Maybe it's an evil, draconic sort of tower?

**Comment by AxlLind** [comment]
Random from github but it's pretty good hehe
