### ISSUE TITLE
Which settings should we have in the create lobby view?

### ISSUE THREAD

**Issue by angloth** [johnnil/Lifelink#7]
Which settings should be available to the host when creating a lobby?

* Should the host be able to decide how many players that should be able to join or should it be fluently changed when new players join or leave the lobby?

* Should the host be able to set the initial life total in the lobby? 

* Should there be a setting for different game modes?

* Should the host be able to set a game time?

* Any more options?

Or maybe we want it so that immediately after clicking "create lobby" a new lobby with some standard settings is created, and the host then can change the settings throughout the game. Maybe this interaction is more fluent but if it's common to play with different settings then an initial view where the host sets the settings is more optimal?

**Comment by sinderwing** [comment]
1. Fluent change makes for less options that the user has to go through and it's hardly going to be abused by uninvited players since it's local.

2. Yes. Different game modes require different starting life totals. In fringe cases, the life totals start out inhomogenous, but for simplicity we can ignore it. **Host sets everyone's life total at the same time**

3. I don't think there's a need for that. The function our app fills is the same for any game mode, of the top of my head.

4. If we implement the chess clock function, yes, absolutely.

As for the last comment, we'd then have to either have lobby "profiles" or remember what the host did last time since someone may play EDH all the time or just standard rules all the time and if we try one-size-fits-all, someone will  get annoyed a lot. I think it'd be best to save the parameters for the last game.

**Comment by angloth** [comment]
1. Ok, but what if the app is being used at a large network at a convention for example? I think that maybe having a setting for having the lobby open or closed is a good idea. I created the issue #9 to discuss this.

2. Wouldn't a solution be to select gamemode in creation menu then? Or is it common to have different starting lives even in the same gamemode?

3. Yea I guess but I think it would look nice maybe. It also upons up the possibility for more features such as Commander focused damage tracking.

4. Agreed.

Yes I agree, so a creation menu of some sort before initializing the lobby sounds like a better way of doing it.

**Comment by sinderwing** [comment]
1. It's a nice feature, but then we're splitting our focus to cater to large conventions. I've been thinking this is something we do for small playgroups first and foremost, since it's realistically the only audience we'll have to begin with.

2. The problem with that is that *a lot of game modes share starting life*, meaning 20 life is the value for the keys Sealed, Draft, Standard, Modern, FFA, Star, French EDH, 1v1 EDH, Pauper, Frontier ... You get the point :) I think it's easier to skip the keys and just have the values 20, 30 and 40 from the get-go.

**Comment by angloth** [comment]
1. Followed this up in #9 

2. Yes setting the life directly between common starting values would be a more straight forward I agree. But if we set the game mode instead it gives us the starting life automatically (right?) and we get the possibility for special game mode functionality and the game mode can be displayed in the lobby browsing menu. Although I think setting the life directly might be better anyway.

**Comment by sinderwing** [comment]
2. I mean, I wouldn't want to scroll down a list of 20 items to find the one-out-of-three result I'm looking for. It's expected that the player knows what life total the want so I'd much rather give that freedom to the player :)

**Comment by angloth** [comment]
Sounds good.
